CREATE TABLE IF NOT EXISTS tickets (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ticket_number       VARCHAR(40) NOT NULL,
    status              ENUM('open','in_progress','pending','closed','cancelled') NOT NULL DEFAULT 'open',
    report_date         DATE NOT NULL,
    reporter_name       VARCHAR(150) NOT NULL,
    dealer_id           BIGINT UNSIGNED NOT NULL,
    item_id             BIGINT UNSIGNED NOT NULL,
    initial_report      TEXT NOT NULL,
    checking_notes      TEXT NULL DEFAULT NULL,
    solution            TEXT NULL DEFAULT NULL,
    started_at          DATETIME NOT NULL,
    finished_at         DATETIME NULL DEFAULT NULL,
    lead_time_seconds   INT NULL DEFAULT NULL,
    assigned_user_id    BIGINT UNSIGNED NULL DEFAULT NULL,
    created_by          BIGINT UNSIGNED NOT NULL,
    updated_by          BIGINT UNSIGNED NULL DEFAULT NULL,
    closed_by           BIGINT UNSIGNED NULL DEFAULT NULL,
    closed_at           DATETIME NULL DEFAULT NULL,
    created_at          DATETIME NOT NULL,
    updated_at          DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_tickets_number (ticket_number),
    KEY idx_tickets_status (status),
    KEY idx_tickets_report_date (report_date),
    KEY idx_tickets_dealer (dealer_id),
    KEY idx_tickets_item (item_id),
    KEY idx_tickets_assigned (assigned_user_id),
    KEY idx_tickets_date_status (report_date, status),
    KEY idx_tickets_dealer_date (dealer_id, report_date),
    KEY idx_tickets_item_date (item_id, report_date),
    CONSTRAINT fk_tickets_dealer       FOREIGN KEY (dealer_id)        REFERENCES dealers (id) ON DELETE RESTRICT,
    CONSTRAINT fk_tickets_item         FOREIGN KEY (item_id)          REFERENCES items   (id) ON DELETE RESTRICT,
    CONSTRAINT fk_tickets_assigned     FOREIGN KEY (assigned_user_id) REFERENCES users   (id) ON DELETE SET NULL,
    CONSTRAINT fk_tickets_created_by   FOREIGN KEY (created_by)       REFERENCES users   (id) ON DELETE RESTRICT,
    CONSTRAINT fk_tickets_updated_by   FOREIGN KEY (updated_by)       REFERENCES users   (id) ON DELETE SET NULL,
    CONSTRAINT fk_tickets_closed_by    FOREIGN KEY (closed_by)        REFERENCES users   (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
